#!/usr/bin/env bash
# Generated by: claude-sonnet-4-6
# Generation date: 2026-04-06
# Usage: scripts/lint-yaml.sh [--strict]
# Default: fail on errors only. --strict: fail on errors and warnings.
set -euo pipefail

STRICT=false
for arg in "$@"; do
  case "$arg" in
    --strict) STRICT=true ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

YAMLLINT_ARGS=()
if [[ "$STRICT" == "true" ]]; then
  YAMLLINT_ARGS+=(--strict)
fi

exec yamllint "${YAMLLINT_ARGS[@]}" \
  .github/workflows/ \
  .github/dependabot.yml \
  .yamllint.yml
