#!/usr/bin/env bash
# Generated by: claude-sonnet-4-6
# Generation date: 2026-04-06
# Usage: scripts/lint-dockerfile.sh [--strict]
# Default: --failure-threshold error. --strict: --failure-threshold warning.
set -euo pipefail

STRICT=false
for arg in "$@"; do
  case "$arg" in
    --strict) STRICT=true ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

THRESHOLD=error
if [[ "$STRICT" == "true" ]]; then
  THRESHOLD=warning
fi

DOCKERFILES=(Dockerfile .devcontainer/Dockerfile)

exit_code=0
for df in "${DOCKERFILES[@]}"; do
  echo "--- hadolint: $df ---"
  hadolint --failure-threshold "$THRESHOLD" "$df" || exit_code=$?
done

exit "$exit_code"
